version: '3.8'
services:
  mongo:
    image: mongo:7
    container_name: leads_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: leads_server
    env_file: ./server/.env
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules

volumes:
  mongo_data:
